/*
    Plugin-SDK (Grand Theft Auto 3) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eCamMode
{
  MODE_NONE = 0,
  MODE_TOPDOWN = 1,
  MODE_GTACLASSIC = 2,
  MODE_BEHINDCAR = 3,
  MODE_FOLLOWPED = 4,
  MODE_AIMING = 5,
  MODE_DEBUG = 6,
  MODE_SNIPER = 7,
  MODE_ROCKETLAUNCHER = 8,
  MODE_MODELVIEW = 9,
  MODE_BILL = 10,
  MODE_SYPHON = 11,
  MODE_CIRCLE = 12,
  MODE_CHEESYZOOM = 13,
  MODE_WHEELCAM = 14,
  MODE_FIXED = 15,
  MODE_1STPERSON = 16,
  MODE_FLYBY = 17,
  MODE_CAM_ON_A_STRING = 18,
  MODE_REACTION = 19,
  MODE_FOLLOW_PED_WITH_BIND = 20,
  MODE_CHRIS = 21,
  MODE_BEHINDBOAT = 22,
  MODE_PLAYER_FALLEN_WATER = 23,
  MODE_CAM_ON_TRAIN_ROOF = 24,
  MODE_CAM_RUNNING_SIDE_TRAIN = 25,
  MODE_BLOOD_ON_THE_TRACKS = 26,
  MODE_IM_THE_PASSENGER_WOOWOO = 27,
  MODE_SYPHON_CRIM_IN_FRONT = 28,
  MODE_PED_DEAD_BABY = 29,
  MODE_PILLOWS_PAPS = 30,
  MODE_LOOK_AT_CARS = 31,
  MODE_ARRESTCAM_ONE = 32,
  MODE_ARRESTCAM_TWO = 33,
  MODE_M16_1STPERSON = 34,
  MODE_SPECIAL_FIXED_FOR_SYPHON = 35,
  MODE_FIGHT_CAM = 36,
  MODE_TOP_DOWN_PED = 37,
  MODE_SNIPER_RUNABOUT = 38,
  MODE_ROCKETLAUNCHER_RUNABOUT = 39,
  MODE_1STPERSON_RUNABOUT = 40,
  MODE_M16_1STPERSON_RUNABOUT = 41,
  MODE_FIGHT_CAM_RUNABOUT = 42,
  MODE_EDITOR = 43,
  MODE_HELICANNON_1STPERSON = 44,
};
